sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t irwaank/client_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true irwaank/client_test npm run test -- --coverage

after_success:
  # Build docker image for production 
  - docker build -t irwaank/multi-docker-client ./client
  - docker build -t irwaank/multi-docker-nginx ./nginx
  - docker build -t irwaank/multi-docker-server ./server
  - docker build -t irwaank/multi-docker-worker ./worker

  # Login to docker hub via docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Docker push
  - docker push irwaank/multi-docker-client
  - docker push irwaank/multi-docker-nginx
  - docker push irwaank/multi-docker-server
  - docker push irwaank/multi-docker-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-southeast-1"
#   # The name of elasticbeanstalk
#   app: "docker_udemy"
#   env: "Dockerudemy-env-1"
#   bucket_name: "elasticbeanstalk-ap-southeast-1-472653352833"
#   # The "bucket_path" should exaclty same with value of "app"
#   bucket_path: "docker_udemy"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"